name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    # Install all the dependencies
    - name: Install dependencies
      run: |
        sudo apt install gcc libgl1-mesa-dev xorg-dev
        go version
        go get ./...
        go get fyne.io/fyne/v2
        go get fyne.io/fyne/v2/cmd/fyne_demo/
        go get fyne.io/fyne/v2/cmd/fyne
        
        
    - name: Build
      run: go build -v ./main.go
