name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    # Install all the dependencies
    - name: Install dependencies
      run: |
        go version
        go get fyne.io/fyne/v2
        go get fyne.io/fyne/v2/cmd/fyne_demo/
        
    - name: Build
      run: go build -v ./main.go

    - name: Test
      run: go test -v ./main.go
